apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  labels:
    app: mlops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-app
        image: ${DOCKER_REGISTRY}/mlops-app:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: MODEL_PATH
          value: "/app/data/models"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-app-service
spec:
  selector:
    app: mlops-app
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer 